 # Jordan Hall-Truong
... # 3/8/2025
... # P2LAB2
... 
... 
... vehicle_mpg = {
... 
"Camaro": 18.21,
... 
"Prius": 52.36,
... 
"Model S": 110,
... 
"Silverado": 26
... }
... 
... keys = vehicle_mpg.keys()
... 
... print(f'dict_keys({keys})')
... 
... vehicle = input("Enter a vehicle to see its mpg: ")
... 
... if vehicle in vehicle_mpg:
... 
print(f"The {vehicle} gets {vehicle_mpg[vehicle]} mpg.")
... 
... 
miles = float(input(f"How many miles will you drive the {vehicle}: "))
... 
... 
gallons_needed = miles / vehicle_mpg[vehicle]
... 
... 
print(f"{gallons_needed:.2f} gallon(s) of gas are needed to drive the {vehicle} {miles} miles.")
... else:
